Repository minio/operator, pull requests merged in 2022-08, with the labels that each got.

#1241 Using container image digests from RedHat Registry
  olm-post-script.sh
  olm.sh
Labels: bug, fixed

#1247 fix: function name typo
  kubectl-minio/cmd/init.go
Labels: enhancement

#1248 To fix tls issue in OpenShift
  resources/base/service.yaml
Labels: enhancement

#1179 Adding automation script to update version in Community Catalog
  community-operators/update-community-operator.sh
Labels: community
