Repository minio/operator, pull requests merged in 2023-10, with the labels that each got.

#1788 Adding back Usable Capacity and Internal
  pkg/controller/monitoring.go
Labels: community

#1800 Support k8s secrets in console pod
  pkg/certs/certs.go
  pkg/certs/const.go
Labels: community

#1783 Create buckets upon tenant creation or after tenant creation
  pkg/controller/main-controller.go
Labels: enhancement

#1821 Revert change as field is actually needed
  helm/operator/templates/console-configmap.yaml
  helm/operator/templates/console-deployment.yaml
  helm/operator/templates/console-ingress.yaml
  helm/operator/templates/console-secret.yaml
  helm/operator/templates/console-service.yaml
  helm/operator/templates/console-serviceaccount.yaml
  helm/operator/templates/operator-deployment.yaml
  helm/operator/templates/operator-service.yaml
  helm/operator/templates/operator-serviceaccount.yaml
  helm/operator/templates/sts-service.yaml
Labels: bug

#1837 fix: create bucket make a conflict status for tenant.
  pkg/apis/minio.min.io/v2/helper.go
  pkg/controller/main-controller.go
  pkg/controller/operator.go
Labels: bug fix
