Repository minio/operator, pull requests merged in 2023-09, with the labels that each got.

#1739 document `extraResources` field in tenant helm chart
  helm/tenant/values.yaml
Labels: documentation

#1754 feat: add sidecar resource to Sidecar container
  docs/tenant_crd.adoc
  helm/operator/templates/minio.min.io_tenants.yaml
  pkg/apis/minio.min.io/v2/types.go
  pkg/resources/statefulsets/minio-statefulset.go
  resources/base/crds/minio.min.io_tenants.yaml
Labels: community

#1758 Warn to use XFS as File system type in AWS EBS
  helm/tenant/values.yaml
Labels: documentation

#1757 Fix CRD docs
  Makefile
  docs/policybinding_crd.adoc
  docs/templates/config.yaml
  docs/tenant_crd.adoc
  pkg/apis/minio.min.io/v2/types.go
Labels: documentation

#1767 fix: avoid panic in operator-ca secret checks
  pkg/controller/main-controller.go
  pkg/controller/minio.go
Labels: bug

#1777 Avoid flooding Operator log
  pkg/runtime/sync.go
Labels: enhancement
