Repository minio/operator, pull requests merged in 2023-06, with the labels that each got.

#1616 Applying same console fix for the subpath issue
  api/configure_operator.go
  cmd/operator/ui.go
  web-app/src/api/index.ts
Labels: bug

#1637 change nodeAffinity to And
  api/tenant-handlers.go
Labels: bug, enhancement

#1648 Add Pod Topology Spread Constraints
  examples/kustomization/base/tenant.yaml
Labels: consistency

#1631 Adding useful information to trust cert-manager cert for minio
  examples/kustomization/tenant-certmanager/certificates.yaml
Labels: documentation

#1594 Warn user about the proper use of subPath field
  examples/kustomization/base/tenant.yaml
  helm/tenant/values.yaml
Labels: consistency
