Repository minio/operator, pull requests merged in 2023-04, with the labels that each got.

#1546 Fixing issue due to missing tenant being removed
  pkg/controller/main-controller.go
Labels: bug

#1561 To add back kubeconfig flag missing in v5.0.x
  cmd/operator/controller.go
  pkg/controller/controller.go
Labels: enhancement

#1549 Let user select their own values
  olm-post-script.sh
Labels: catalogs

#1565 OpenShift 4.7 has reached its end of life
  olm.sh
Labels: dependencies

#1566 One replica only for Code Ready Containers with one node
  olm.sh
Labels: dependencies

#1569 To provide upgrade channel for Operator
  olm.sh
Labels: dependencies

#1570 Supporting different archs and OSes
  olm.sh
Labels: dependencies

#1571 Files to be committed to the Catalogs
  bundles/certified-operators/5.0.3/manifests/minio-operator.clusterserviceversion.yaml
  bundles/certified-operators/5.0.3/manifests/operator_v1_service.yaml
  bundles/certified-operators/5.0.3/manifests/sts_v1_service.yaml
  bundles/certified-operators/5.0.3/metadata/annotations.yaml
  bundles/community-operators/5.0.3/manifests/minio-operator.clusterserviceversion.yaml
  bundles/community-operators/5.0.3/manifests/operator_v1_service.yaml
  bundles/community-operators/5.0.3/manifests/sts_v1_service.yaml
  bundles/community-operators/5.0.3/metadata/annotations.yaml
  bundles/redhat-marketplace/5.0.3/manifests/minio-operator-rhmp.clusterserviceversion.yaml
  bundles/redhat-marketplace/5.0.3/manifests/operator_v1_service.yaml
  bundles/redhat-marketplace/5.0.3/manifests/sts_v1_service.yaml
  bundles/redhat-marketplace/5.0.3/metadata/annotations.yaml
  certified-operators/manifests/minio-operator.clusterserviceversion.yaml
  certified-operators/manifests/operator_v1_service.yaml
  certified-operators/manifests/sts_v1_service.yaml
  community-operators/manifests/minio-operator.clusterserviceversion.yaml
  community-operators/manifests/operator_v1_service.yaml
  community-operators/manifests/sts_v1_service.yaml
  manifests/minio-operator-rhmp.clusterserviceversion.yaml
  manifests/operator_v1_service.yaml
  manifests/sts_v1_service.yaml
  metadata/annotations.yaml
  redhat-marketplace/manifests/minio-operator-rhmp.clusterserviceversion.yaml
  redhat-marketplace/manifests/operator_v1_service.yaml
  redhat-marketplace/manifests/sts_v1_service.yaml
Labels: dependencies

#1573 OLM: Conversion webhook is no longer needed
  olm.sh
Labels: dependencies

#1574 OLM: Correcting UI image
  olm-post-script.sh
Labels: dependencies

#1589 remove `--default-console-image` parameter
  kubectl-minio/cmd/init.go
Labels: enhancement
