Repository minio/operator, pull requests merged in 2023-11, with the labels that each got.

#1827 DOCS-1021: Attempting to add autoyaml docs for Helm charts
  helm/operator/values.yaml
  helm/tenant/values.yaml
Labels: documentation

#1847 mounting Operator CA in minio not longer required
  .gitignore
  pkg/resources/statefulsets/minio-statefulset.go
Labels: community

#1863 Prepare for the addition of new CRD
  docs/tenant_crd.adoc
  go.mod
  go.sum
  k8s/update-codegen.sh
  kubectl-minio/go.mod
  kubectl-minio/go.sum
  pkg/apis/minio.min.io/v2/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/minio.min.io/v2/auditconfig.go
  pkg/client/applyconfiguration/minio.min.io/v2/logconfig.go
  pkg/client/applyconfiguration/minio.min.io/v2/logdbconfig.go
  pkg/client/applyconfiguration/minio.min.io/v2/pool.go
  pkg/client/applyconfiguration/minio.min.io/v2/prometheusconfig.go
  pkg/client/applyconfiguration/minio.min.io/v2/s3features.go
  pkg/client/applyconfiguration/minio.min.io/v2/sidecars.go
  pkg/client/applyconfiguration/minio.min.io/v2/tenantspec.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/informers/externalversions/factory.go
Labels: upgrade
