Repository minio/operator, pull requests merged in 2024-03, with the labels that each got.

#2018 Make decommission test more reliable
  testing/common.sh
  testing/decommission-test.sh
  testing/verify-data.sh
Labels: enhancement

#2032 Document boolean behaviour of helm .secrets.existingSecret
  helm/tenant/templates/tenant-configuration.yaml
  helm/tenant/values.yaml
Labels: documentation

#2031 feat: Create job and Watch job status for minioJob
  pkg/controller/job-controller.go
  pkg/utils/miniojob/minioJob.go
  pkg/utils/miniojob/minioJob_test.go
Labels: community, Addition

#2052 upgrading the floor version of k8s to test
  testing/kind-config-floor.yaml
Labels: test
