Repository minio/operator, pull requests merged in 2024-04, with the labels that each got.

#2060 To fix vulnerability
  go.mod
  go.sum
Labels: vulnerability

#2059 To use port number instead of port name
  helm/operator/templates/console-ingress.yaml
  helm/operator/values.yaml
Labels: bug fix

#2062 To fix goreleaser
  .github/workflows/goreleaser.yml
  .goreleaser.yml
  kubectl-minio/go.mod
  kubectl-minio/go.sum
Labels: dependencies

#2063 feat: support more type to admin/config/set
  pkg/utils/miniojob/minioJob.go
  pkg/utils/miniojob/minioJob_test.go
  pkg/utils/miniojob/types.go
Labels: Addition

#2070 Fields immutable
  docs/job_crd.adoc
  docs/policybinding_crd.adoc
  docs/tenant_crd.adoc
  helm/operator/templates/job.min.io_jobs.yaml
  helm/operator/templates/minio.min.io_tenants.yaml
  helm/operator/templates/sts.min.io_policybindings.yaml
  pkg/apis/minio.min.io/v2/types.go
  pkg/client/applyconfiguration/job.min.io/v1alpha1/miniojobspec.go
  pkg/client/applyconfiguration/job.min.io/v1alpha1/miniojobstatus.go
  resources/base/crds/job.min.io_miniojobs.yaml
  resources/base/crds/minio.min.io_tenants.yaml
  resources/base/crds/sts.min.io_policybindings.yaml
Labels: enhancement

#2071 Correct typo
  pkg/utils/miniojob/minioJob.go
  pkg/utils/miniojob/minioJob_test.go
  pkg/utils/miniojob/types.go
Labels: typo

#2049 fix: no default label when nothing set for console service
  pkg/resources/services/service.go
Labels: Addition

#2051 Deprecate the Krew plugin
  .gitignore
  .goreleaser.yml
  Makefile
  README.md
  docs/console.md
  docs/expansion.md
  docs/kes.md
  docs/nginx-ingress.md
  docs/tenant-creation.md
  krew-plugin.md
  kubectl-minio/CREDITS
  kubectl-minio/LICENSE
  kubectl-minio/README.md
  kubectl-minio/cmd/color.go
  kubectl-minio/cmd/delete.go
  kubectl-minio/cmd/helpers/constants.go
  kubectl-minio/cmd/helpers/helpers.go
  kubectl-minio/cmd/init.go
  kubectl-minio/cmd/kubectl-minio.go
  kubectl-minio/cmd/proxy.go
  kubectl-minio/cmd/resources/common.go
  kubectl-minio/cmd/resources/deployment.go
  kubectl-minio/cmd/resources/secret.go
  kubectl-minio/cmd/resources/tenant.go
  kubectl-minio/cmd/tenant-create.go
  kubectl-minio/cmd/tenant-delete.go
  kubectl-minio/cmd/tenant-events.go
  kubectl-minio/cmd/tenant-expand.go
  kubectl-minio/cmd/tenant-info.go
  kubectl-minio/cmd/tenant-list.go
  kubectl-minio/cmd/tenant-report.go
  kubectl-minio/cmd/tenant-status.go
  kubectl-minio/cmd/tenant-upgrade.go
  kubectl-minio/cmd/tenant.go
  kubectl-minio/cmd/version.go
  kubectl-minio/go.mod
  kubectl-minio/go.sum
  kubectl-minio/main.go
  package.sh
  release.sh
  testing/common.sh
  update-operator-krew.py
Labels: deprecation

#2075 To remove decommission test from upstream
  .github/workflows/kubernetes-tests.yml
Labels: removal

#2078 Redhat marketplace publish 5.0.14
  bundles/certified-operators/5.0.14/manifests/minio-operator.clusterserviceversion.yaml
  bundles/certified-operators/5.0.14/metadata/annotations.yaml
  bundles/community-operators/5.0.14/manifests/minio-operator.clusterserviceversion.yaml
  bundles/community-operators/5.0.14/metadata/annotations.yaml
  bundles/redhat-marketplace/5.0.14/manifests/minio-operator-rhmp.clusterserviceversion.yaml
  bundles/redhat-marketplace/5.0.14/metadata/annotations.yaml
  certified-operators/manifests/minio-operator.clusterserviceversion.yaml
  community-operators/manifests/minio-operator.clusterserviceversion.yaml
  manifests/minio-operator-rhmp.clusterserviceversion.yaml
  metadata/annotations.yaml
  olm.sh
  redhat-marketplace/manifests/minio-operator-rhmp.clusterserviceversion.yaml
Labels: release

#2072 Allow to run with restricted pod security standards
  api/tenant-handlers.go
  examples/kustomization/base/tenant.yaml
  examples/kustomization/tenant-lite/tenant.yaml
  helm/operator/values.yaml
  helm/tenant/values.yaml
  resources/base/console-ui.yaml
  resources/base/deployment.yaml
  resources/base/namespace.yaml
  testing/common.sh
Labels: Addition

#2081 To fix upgrade test
  testing/common.sh
Labels: fix

#1835 Add Lifecycle hooks configuration to Tenant
  docs/tenant_crd.adoc
  helm/operator/templates/minio.min.io_tenants.yaml
  helm/tenant/templates/tenant.yaml
  helm/tenant/values.yaml
  pkg/apis/minio.min.io/v2/types.go
  pkg/resources/statefulsets/minio-statefulset.go
  resources/base/crds/minio.min.io_tenants.yaml
Labels: Addition

#2084 Only create marketplace publish after container image have been published
  Makefile
  community-operators/update-community-operator.sh
  olm-post-script.sh
  olm.sh
  redhat-marketplace/update-redhat-marketplace-operator.sh
Labels: enhancement
