Repository minio/operator, pull requests merged in 2024-01, with the labels that each got.

#1925 Add a PoolLabel selector to PodAntiAffinity
  kubectl-minio/cmd/resources/common.go
Labels: bug fix

#1883 MinIO Job CRD
  Makefile
  docs/job_crd.adoc
  helm/operator/templates/job.min.io_jobs.yaml
  k8s/update-codegen.sh
  pkg/apis/job.min.io/register.go
  pkg/apis/job.min.io/v1alpha1/doc.go
  pkg/apis/job.min.io/v1alpha1/register.go
  pkg/apis/job.min.io/v1alpha1/types.go
  pkg/apis/job.min.io/v1alpha1/zz_generated.deepcopy.go
  pkg/client/applyconfiguration/job.min.io/v1alpha1/commandspec.go
  pkg/client/applyconfiguration/job.min.io/v1alpha1/commandstatus.go
  pkg/client/applyconfiguration/job.min.io/v1alpha1/miniojob.go
  pkg/client/applyconfiguration/job.min.io/v1alpha1/miniojobspec.go
  pkg/client/applyconfiguration/job.min.io/v1alpha1/miniojobstatus.go
  pkg/client/applyconfiguration/job.min.io/v1alpha1/tenantref.go
  pkg/client/applyconfiguration/utils.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/job.min.io/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/job.min.io/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/job.min.io/v1alpha1/fake/fake_job.min.io_client.go
  pkg/client/clientset/versioned/typed/job.min.io/v1alpha1/fake/fake_miniojob.go
  pkg/client/clientset/versioned/typed/job.min.io/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/job.min.io/v1alpha1/job.min.io_client.go
  pkg/client/clientset/versioned/typed/job.min.io/v1alpha1/miniojob.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/job.min.io/interface.go
  pkg/client/informers/externalversions/job.min.io/v1alpha1/interface.go
  pkg/client/informers/externalversions/job.min.io/v1alpha1/miniojob.go
  pkg/client/listers/job.min.io/v1alpha1/expansion_generated.go
  pkg/client/listers/job.min.io/v1alpha1/miniojob.go
  resources/base/crds/job.min.io_miniojobs.yaml
Labels: new feature

#1950 Use nearest zero-based pool name for expansion
  kubectl-minio/cmd/resources/common.go
  kubectl-minio/cmd/tenant-expand.go
  web-app/src/common/utils.ts
Labels: operator-console

#1957 Add RBAC Permissions to Operator for Jobs
  resources/base/cluster-role.yaml
Labels: permissions

#1958 Adding Job CRD
  resources/base/crds/kustomization.yaml
Labels: Addition
