Repository minio/operator, pull requests merged in 2024-02, with the labels that each got.

#1959 Add decommission test
  .github/workflows/kubernetes-tests.yml
  testing/common.sh
  testing/configurations/debug-pod.yaml
  testing/create-alias.sh
  testing/decommission-script.sh
  testing/decommission-test.sh
  testing/install-mc.sh
  testing/upload-data.sh
  testing/verify-data.sh
Labels: test

#1971 Multitenancy Support for External Certs
  pkg/controller/operator.go
Labels: enhancement

#1947 Using kustomize rather than krew plugin for the readme
  README.md
  krew-plugin.md
Labels: documentation

#1949 Operator Console OpenID configuration
  examples/kustomization/operator-external-idp-oid/README.md
  examples/kustomization/operator-external-idp-oid/console-deployment.yaml
  examples/kustomization/operator-external-idp-oid/console-tls-secret.yaml
  examples/kustomization/operator-external-idp-oid/kustomization.yaml
Labels: documentation

#1981 Create statefulset even on cert update failure
  pkg/controller/main-controller.go
Labels: bug fix

#1978 The Job Controller Should Run
  pkg/controller/controller.go
  pkg/controller/job-controller.go
  pkg/controller/main-controller.go
Labels: enhancement, Addition

#1988 Recommend trivial parity
  web-app/src/common/utils.ts
  web-app/src/screens/Console/Tenants/AddTenant/Steps/SizePreview.tsx
  web-app/src/screens/Console/Tenants/AddTenant/Steps/TenantResources/TenantSize.tsx
  web-app/src/screens/Console/Tenants/AddTenant/Steps/TenantResources/TenantSizeResources.tsx
Labels: operator-console

#1992 Using clientset to read the Custom Resource
  pkg/controller/job-controller.go
  pkg/controller/main-controller.go
Labels: declarative
