Repository minio/operator, pull requests merged in 2024-06, with the labels that each got.

#2143 To fix React No Warnings & Prettified Test
  web-app/package.json
  web-app/yarn.lock
Labels: vulnerability

#2151 feat: support command for minioJob
  helm/operator/templates/job.min.io_jobs.yaml
  pkg/apis/job.min.io/v1alpha1/types.go
  pkg/controller/job-controller.go
  pkg/utils/miniojob/types.go
  resources/base/crds/job.min.io_miniojobs.yaml
Labels: jobCRD

#2162 Correcting the name of the variable
  examples/kustomization/operator-external-idp-oid/README.md
Labels: IdP

#2168 Allow Tolerations to have Seconds undefined
  api/tenant-handlers.go
  web-app/src/screens/Console/Common/TolerationSelector/TolerationSelector.tsx
  web-app/src/screens/Console/Tenants/AddTenant/Steps/Affinity.tsx
  web-app/src/screens/Console/Tenants/AddTenant/createTenantSlice.ts
  web-app/src/screens/Console/Tenants/TenantDetails/Pools/AddPool/PoolPodPlacement.tsx
  web-app/src/screens/Console/Tenants/TenantDetails/Pools/AddPool/addPoolSlice.ts
  web-app/src/screens/Console/Tenants/TenantDetails/Pools/Details/PoolDetails.tsx
  web-app/src/screens/Console/Tenants/TenantDetails/Pools/EditPool/EditPoolPlacement.tsx
  web-app/src/screens/Console/Tenants/TenantDetails/Pools/EditPool/editPoolSlice.ts
Labels: bug fix

#2166 security: Using k8s idp instead of providing console-sa
  api/config.go
  api/config_test.go
  api/login.go
Labels: security

#2172 Wait for MinIO to be ready before proceeding with any further tasks.
  .gitignore
  pkg/controller/main-controller.go
Labels: improvement
