Repository minio/operator, pull requests merged in 2025-04, with the labels that each got.

#2419 Update MinIO and KES base images.
  docs/policybinding_crd.adoc
  docs/templates/asciidoctor/gv_list.tpl
  docs/tenant_crd.adoc
  examples/kustomization/base/tenant.yaml
  helm/tenant/values.yaml
  pkg/apis/minio.min.io/v2/constants.go
Labels: security-fix

#2422 Bugfix: error applying `operator.sidecarImage`
  helm/operator/templates/operator-deployment.yaml
Labels: bug fix

#2412 Fix issue with Helm configuration secret
  helm/tenant/templates/checks.yaml
  helm/tenant/templates/tenant-configuration.yaml
  helm/tenant/templates/tenant.yaml
  helm/tenant/values.yaml
Labels: bug

#2417 Create SECURITY.md
  SECURITY.md
Labels: security

#2426 Replace `golang.org/x/crypto` to `v0.36.0`
  go.mod
  go.sum
  sidecar/go.mod
  sidecar/go.sum
Labels: security-fix

#2423 Release 7.1.0
  README.md
  docs/policybinding_crd.adoc
  docs/templates/asciidoctor/gv_list.tpl
  docs/tenant_crd.adoc
  examples/kustomization/base/tenant.yaml
  helm/operator/Chart.yaml
  helm/operator/templates/minio.min.io_tenants.yaml
  helm/operator/templates/sts.min.io_policybindings.yaml
  helm/operator/values.yaml
  helm/tenant/Chart.yaml
  helm/tenant/values.yaml
  pkg/apis/minio.min.io/v2/constants.go
  pkg/apis/minio.min.io/v2/types.go
  pkg/apis/sts.min.io/v1beta1/types.go
  pkg/client/applyconfiguration/minio.min.io/v2/tenantspec.go
  resources/base/crds/minio.min.io_tenants.yaml
  resources/base/crds/sts.min.io_policybindings.yaml
  resources/base/deployment.yaml
  resources/kustomization.yaml
  testing/console-tenant+kes.sh
Labels: release

#2375 Add Documentation for Replication Using a Load Balancer
  docs/nginx-ingress.md
Labels: documentation

#2430 fix: wrong indentation in env causing helm install failure
  helm/operator/templates/operator-deployment.yaml
Labels: helm chart

#2441 update operator package reference
  sidecar/go.mod
Labels: security-fix
