Repository minio/operator, pull requests merged in 2025-06, with the labels that each got.

#2454 Use `.Release.namespace` in tenant Helm chart
  helm/tenant/templates/api-ingress.yaml
  helm/tenant/templates/console-ingress.yaml
  helm/tenant/templates/kes-configuration-secret.yaml
  helm/tenant/templates/tenant-configuration.yaml
  helm/tenant/templates/tenant.yaml
Labels: bug

#2462 Add document describing nelm usage
  NELM.md
  UPGRADE.md
Labels: documentation

#2466 Add `sideCars` to the MinIO tenant Helm chart
  helm/tenant/templates/tenant.yaml
  helm/tenant/values.yaml
Labels: enhancement
